CNode0: Q1ZhbHVlMF9keW5hbWlj
CNode1: CValue1_inline
CNode2:
  CNode2_1: CValue2_1_dynamic
  CNode2_2: CValue2_2_file
CNode3:
  CNode3_1: CValue3_1_inline CValue3_1_dynamic text
  CNode3_2: CValue3_2_inline
